/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WcLoader {}
  interface WcRipple {}
  interface WcSpinners {}
}

declare global {


  interface HTMLWcLoaderElement extends Components.WcLoader, HTMLStencilElement {}
  var HTMLWcLoaderElement: {
    prototype: HTMLWcLoaderElement;
    new (): HTMLWcLoaderElement;
  };

  interface HTMLWcRippleElement extends Components.WcRipple, HTMLStencilElement {}
  var HTMLWcRippleElement: {
    prototype: HTMLWcRippleElement;
    new (): HTMLWcRippleElement;
  };

  interface HTMLWcSpinnersElement extends Components.WcSpinners, HTMLStencilElement {}
  var HTMLWcSpinnersElement: {
    prototype: HTMLWcSpinnersElement;
    new (): HTMLWcSpinnersElement;
  };
  interface HTMLElementTagNameMap {
    'wc-loader': HTMLWcLoaderElement;
    'wc-ripple': HTMLWcRippleElement;
    'wc-spinners': HTMLWcSpinnersElement;
  }
}

declare namespace LocalJSX {
  interface WcLoader extends JSXBase.HTMLAttributes<HTMLWcLoaderElement> {}
  interface WcRipple extends JSXBase.HTMLAttributes<HTMLWcRippleElement> {}
  interface WcSpinners extends JSXBase.HTMLAttributes<HTMLWcSpinnersElement> {}

  interface IntrinsicElements {
    'wc-loader': WcLoader;
    'wc-ripple': WcRipple;
    'wc-spinners': WcSpinners;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


